"""add pipeline metadata engine

Revision ID: 6d3a04d25d1b
Revises: a2b7ec202dc3
Create Date: 2026-08-17 12:08:39.744129
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d3a04d25d1b"
down_revision: str | None = "a2b7ec202dc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_dependencies",
        sa.Column("pipeline_id", sa.String(length=36), nullable=False),
        sa.Column("depends_on_pipeline_id", sa.String(length=36), nullable=False),
        sa.Column(
            "dependency_type",
            sa.Enum("SUCCESS", "COMPLETION", name="dependencytype"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "pipeline_id <> depends_on_pipeline_id",
            name=op.f("ck_pipeline_dependencies_not_self_dependency"),
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_dependencies_depends_on_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_dependencies_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_dependencies")),
        sa.UniqueConstraint(
            "pipeline_id", "depends_on_pipeline_id", name="uq_pipeline_dependencies_pair"
        ),
    )
    op.create_index(
        op.f("ix_pipeline_dependencies_depends_on_pipeline_id"),
        "pipeline_dependencies",
        ["depends_on_pipeline_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_dependencies_is_active"),
        "pipeline_dependencies",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_dependencies_pipeline_id"),
        "pipeline_dependencies",
        ["pipeline_id"],
        unique=False,
    )
    op.create_table(
        "column_mappings",
        sa.Column("step_id", sa.String(length=36), nullable=False),
        sa.Column("source_column", sa.String(length=255), nullable=True),
        sa.Column("target_column", sa.String(length=255), nullable=False),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=100), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["pipeline_steps.id"],
            name=op.f("fk_column_mappings_step_id_pipeline_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_mappings")),
        sa.UniqueConstraint("step_id", "target_column", name="uq_column_mappings_step_target"),
    )
    op.create_index(
        op.f("ix_column_mappings_is_active"), "column_mappings", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_column_mappings_step_id"), "column_mappings", ["step_id"], unique=False
    )
    with op.batch_alter_table("pipeline_steps") as batch_op:
        batch_op.add_column(sa.Column("source_dataset_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("target_dataset_id", sa.String(length=36), nullable=True))
        batch_op.add_column(
            sa.Column(
                "load_strategy",
                sa.Enum(
                    "APPEND",
                    "OVERWRITE",
                    "MERGE",
                    "UPSERT",
                    "SCD_TYPE_1",
                    "SCD_TYPE_2",
                    name="loadstrategy",
                ),
                nullable=True,
            )
        )
        batch_op.create_index(
            op.f("ix_pipeline_steps_source_dataset_id"), ["source_dataset_id"], unique=False
        )
        batch_op.create_index(
            op.f("ix_pipeline_steps_target_dataset_id"), ["target_dataset_id"], unique=False
        )
        batch_op.create_foreign_key(
            op.f("fk_pipeline_steps_target_dataset_id_datasets"),
            "datasets",
            ["target_dataset_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            op.f("fk_pipeline_steps_source_dataset_id_datasets"),
            "datasets",
            ["source_dataset_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.add_column(
        "pipelines",
        sa.Column("schedule_timezone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pipelines", "schedule_timezone")
    with op.batch_alter_table("pipeline_steps") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_pipeline_steps_source_dataset_id_datasets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            op.f("fk_pipeline_steps_target_dataset_id_datasets"), type_="foreignkey"
        )
        batch_op.drop_index(op.f("ix_pipeline_steps_target_dataset_id"))
        batch_op.drop_index(op.f("ix_pipeline_steps_source_dataset_id"))
        batch_op.drop_column("load_strategy")
        batch_op.drop_column("target_dataset_id")
        batch_op.drop_column("source_dataset_id")
    op.drop_index(op.f("ix_column_mappings_step_id"), table_name="column_mappings")
    op.drop_index(op.f("ix_column_mappings_is_active"), table_name="column_mappings")
    op.drop_table("column_mappings")
    op.drop_index(op.f("ix_pipeline_dependencies_pipeline_id"), table_name="pipeline_dependencies")
    op.drop_index(op.f("ix_pipeline_dependencies_is_active"), table_name="pipeline_dependencies")
    op.drop_index(
        op.f("ix_pipeline_dependencies_depends_on_pipeline_id"), table_name="pipeline_dependencies"
    )
    op.drop_table("pipeline_dependencies")
    # ### end Alembic commands ###
