"""create metadata model

Revision ID: a2b7ec202dc3
Revises:
Create Date: 2026-08-13 12:25:41.141539
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a2b7ec202dc3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schedule", sa.String(length=120), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("name", name="uq_pipelines_name"),
    )
    op.create_index(op.f("ix_pipelines_is_active"), "pipelines", ["is_active"], unique=False)
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("DATABASE", "FILE", "API", "STREAM", "CLOUD_STORAGE", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("name", name="uq_sources_name"),
    )
    op.create_index(op.f("ix_sources_is_active"), "sources", ["is_active"], unique=False)
    op.create_table(
        "connections",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("connection_type", sa.String(length=50), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("secret_reference", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_connections_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
        sa.UniqueConstraint("source_id", "name", name="uq_connections_source_name"),
    )
    op.create_index(op.f("ix_connections_is_active"), "connections", ["is_active"], unique=False)
    op.create_index(op.f("ix_connections_source_id"), "connections", ["source_id"], unique=False)
    op.create_table(
        "executions",
        sa.Column("pipeline_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="executionstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.String(length=255), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"], ["pipelines.id"], name=op.f("fk_executions_pipeline_id_pipelines")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("run_id", name="uq_executions_run_id"),
    )
    op.create_index(
        "ix_executions_pipeline_status", "executions", ["pipeline_id", "status"], unique=False
    )
    op.create_table(
        "pipeline_steps",
        sa.Column("pipeline_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum("EXTRACT", "TRANSFORM", "LOAD", "VALIDATE", name="steptype"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_pipeline_steps_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_steps_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_steps")),
        sa.UniqueConstraint("pipeline_id", "name", name="uq_pipeline_steps_pipeline_name"),
        sa.UniqueConstraint("pipeline_id", "position", name="uq_pipeline_steps_pipeline_position"),
    )
    op.create_index(
        op.f("ix_pipeline_steps_is_active"), "pipeline_steps", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_steps_pipeline_id"), "pipeline_steps", ["pipeline_id"], unique=False
    )
    op.create_table(
        "datasets",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=True),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "dataset_type",
            sa.Enum("TABLE", "VIEW", "FILE", "STREAM", name="datasettype"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=1000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_datasets_connection_id_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_datasets_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint(
            "source_id", "namespace", "name", name="uq_datasets_source_namespace_name"
        ),
    )
    op.create_index(op.f("ix_datasets_connection_id"), "datasets", ["connection_id"], unique=False)
    op.create_index(op.f("ix_datasets_is_active"), "datasets", ["is_active"], unique=False)
    op.create_index(op.f("ix_datasets_source_id"), "datasets", ["source_id"], unique=False)
    op.create_table(
        "dataset_columns",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("is_nullable", sa.Boolean(), nullable=False),
        sa.Column("is_primary_key", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "ordinal_position >= 0", name=op.f("ck_dataset_columns_ordinal_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_columns_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_columns")),
        sa.UniqueConstraint("dataset_id", "name", name="uq_dataset_columns_dataset_name"),
        sa.UniqueConstraint(
            "dataset_id", "ordinal_position", name="uq_dataset_columns_dataset_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_dataset_columns_dataset_id"), "dataset_columns", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_columns_is_active"), "dataset_columns", ["is_active"], unique=False
    )
    op.create_table(
        "incremental_configurations",
        sa.Column("pipeline_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=True),
        sa.Column(
            "strategy",
            sa.Enum("FULL", "WATERMARK", "CDC", "APPEND", name="incrementalstrategy"),
            nullable=False,
        ),
        sa.Column("watermark_column", sa.String(length=255), nullable=True),
        sa.Column("initial_value", sa.String(length=1000), nullable=True),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_incremental_configurations_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_incremental_configurations_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incremental_configurations")),
        sa.UniqueConstraint("pipeline_id", name="uq_incremental_config_pipeline"),
    )
    op.create_index(
        op.f("ix_incremental_configurations_dataset_id"),
        "incremental_configurations",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incremental_configurations_is_active"),
        "incremental_configurations",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "transformations",
        sa.Column("step_id", sa.String(length=36), nullable=False),
        sa.Column("input_dataset_id", sa.String(length=36), nullable=True),
        sa.Column("output_dataset_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("transformation_type", sa.String(length=80), nullable=False),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["input_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_transformations_input_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["output_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_transformations_output_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["pipeline_steps.id"],
            name=op.f("fk_transformations_step_id_pipeline_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transformations")),
        sa.UniqueConstraint("step_id", "name", name="uq_transformations_step_name"),
    )
    op.create_index(
        op.f("ix_transformations_input_dataset_id"),
        "transformations",
        ["input_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transformations_is_active"), "transformations", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_transformations_output_dataset_id"),
        "transformations",
        ["output_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transformations_step_id"), "transformations", ["step_id"], unique=False
    )
    op.create_table(
        "quality_rules",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("column_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rule_type", sa.String(length=80), nullable=False),
        sa.Column(
            "severity", sa.Enum("INFO", "WARNING", "ERROR", name="qualityseverity"), nullable=False
        ),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["dataset_columns.id"],
            name=op.f("fk_quality_rules_column_id_dataset_columns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_quality_rules_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_rules")),
        sa.UniqueConstraint("dataset_id", "name", name="uq_quality_rules_dataset_name"),
    )
    op.create_index(
        op.f("ix_quality_rules_column_id"), "quality_rules", ["column_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_rules_dataset_id"), "quality_rules", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_rules_is_active"), "quality_rules", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quality_rules_is_active"), table_name="quality_rules")
    op.drop_index(op.f("ix_quality_rules_dataset_id"), table_name="quality_rules")
    op.drop_index(op.f("ix_quality_rules_column_id"), table_name="quality_rules")
    op.drop_table("quality_rules")
    op.drop_index(op.f("ix_transformations_step_id"), table_name="transformations")
    op.drop_index(op.f("ix_transformations_output_dataset_id"), table_name="transformations")
    op.drop_index(op.f("ix_transformations_is_active"), table_name="transformations")
    op.drop_index(op.f("ix_transformations_input_dataset_id"), table_name="transformations")
    op.drop_table("transformations")
    op.drop_index(
        op.f("ix_incremental_configurations_is_active"), table_name="incremental_configurations"
    )
    op.drop_index(
        op.f("ix_incremental_configurations_dataset_id"), table_name="incremental_configurations"
    )
    op.drop_table("incremental_configurations")
    op.drop_index(op.f("ix_dataset_columns_is_active"), table_name="dataset_columns")
    op.drop_index(op.f("ix_dataset_columns_dataset_id"), table_name="dataset_columns")
    op.drop_table("dataset_columns")
    op.drop_index(op.f("ix_datasets_source_id"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_is_active"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_connection_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_pipeline_steps_pipeline_id"), table_name="pipeline_steps")
    op.drop_index(op.f("ix_pipeline_steps_is_active"), table_name="pipeline_steps")
    op.drop_table("pipeline_steps")
    op.drop_index("ix_executions_pipeline_status", table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_connections_source_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_is_active"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_sources_is_active"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_pipelines_is_active"), table_name="pipelines")
    op.drop_table("pipelines")
    # ### end Alembic commands ###
